apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none # use regional-pd instead